version: "2"

services:
  mysql:
    image: mysql:5.7.22
    ports:
      - ${MYSQL_PORT}:3306/tcp
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${MYSQL_TIMEZONE}
    restart: "${RESTART}"
    volumes:
      - mysqldb-vol:/var/lib/mysql
    networks:
      static-mysql:
        ipv4_address: 10.30.50.4

networks:
  static-mysql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24
          gateway: 10.30.50.1

volumes:
  mysqldb-vol:
    driver: local
