version: "2.4"

services:
  mysql:
    image: mysql:5.7.22
    ports:
      - ${MYSQL_PORT}:3306/tcp
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${MYSQL_TIMEZONE}
    restart: "${RESTART}"
    volumes:
      - mysqldb-vol:/var/lib/mysql
    networks:
      mynet:
        ipv4_address: 10.30.51.1

networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: 10.30.51.0/24

volumes:
  mysqldb-vol:
    driver: local
