version: "3.7"

services:
  prometheus:
   image: prom/prometheus
   volumes:
     - prom-vol: /prometheus-data
   configs:
     - prom-configs
   ports:
     - ${HTTP_PORT}:9090
   restart: "${RESTART}"
   network_mode: bridge

volumes:
  prom-vol:
    driver: local
configs:
  prom-configs:
    file: /prometheus-data/prometheus.yml