  #----------------------------------------------------------------------------------------
  #  TICK Stack
  #----------------------------------------------------------------------------------------
version: "2"

services:
  influxdb:
    image: influxdb:1.7-alpine
    volumes:
      # Mount for influxdb data directory
      - influxdb-data:$PWD/var/lib/influxdb
      # Mount for influxdb configuration
      - influxdb-config:$PWD/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - ${INFLUX_DB_PORT}:8086
      - ${INFLUX_ADMIN_PORT}:8082
      # UDP Port
      - ${INFLUX_UDP_PORT}:8089/udp

  telegraf:
    image: telegraf:1.11-alpine
    environment:
      HOSTNAME: "telegraf-getting-started"
    # Telegraf requires network access to InfluxDB
    links:
      - influxdb
    volumes:
      # Mount for telegraf configuration
      - telegraf-conf:$PWD/etc/telegraf/telegraf.conf:ro
      # Mount for Docker API access
      - docker-sock:$PWD/var/run/docker.sock
    depends_on:
#      - rabbitmq
      - influxdb

  kapacitor:
    image: kapacitor:1.5-alpine
    volumes:
      # Mount for kapacitor data directory
      - kapacitor-data:$PWD/var/lib/kapacitor
      # Mount for kapacitor configuration
      - kapacitor-config:$PWD/etc/kapacitor/
    # Kapacitor requires network access to Influxdb
    links:
      - influxdb
    ports:
      # The API for Kapacitor is served on port 9092
      - ${KAPACITOR_PORT}:9092

  chronograf:
    image: chronograf:1.7-alpine
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
    volumes:
      # Mount for chronograf database
      - chronograf-data:$PWD/var/lib/chronograf/
    links:
      # Chronograf requires network access to InfluxDB and Kapacitor
      - influxdb
      - kapacitor
    ports:
      # The WebUI for Chronograf is served on port 8888
      - ${CHRONOGRAF_PORT}:8888
    depends_on:
      - kapacitor
      - influxdb
      - telegraf

volumes:
  influxdb-data:
    driver: local
  influxdb-config:
    driver: local
  telegraf-conf:
    driver: local
  docker-sock:
    driver: local
  kapacitor-data:
    driver: local
  kapacitor-config:
    driver: local
  chronograf-data:
    driver: local