version: '2'

services:

  rstudio:
    image: rocker/rstudio:3.6.1
    build:
      context: .
    environment:
      USER: rstudio
      PASSWORD: ${R_PASSWORD}
      ROOT: "FALSE"
    volumes:
      - path/to/workspace:/home/rstudio
    ports:
      - "${R_PORT}:8787"
    networks:
      - R
  
  rshiny:
    image: rocker/shiny
    volumes:
      - path/to/workspace:/srv/shiny-server
      - /var/logs/shiny:/var/log/shiny-server
    ports:
      - "3838:3838"
    networks:
      - R
    restart: unless-stopped

networks:
  R:
    driver: bridge
© 2019 GitHub, Inc.    

  