version: '2'

services:

  wordpress:
    image: wordpress
    restart: "${RESTART}"
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER=${USERNAME}
      WORDPRESS_DB_PASSWORD=${USERPASSWD}
      WORDPRESS_DB_NAME=${DB_NAME}
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: "${RESTART_DB}"
    environment:
      MYSQL_DATABASE=${DB_NAME}
      MYSQL_USER=${USERNAME}
      MYSQL_PASSWORD=${USERPASSWD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
    driver: local
  db:
    driver: local
